import React from "react";

export const generateMetadata = ({ params }: any) => {
  return {
    title: "Category Page " + params.id,
    description: "Generated by create next app",
  };
};

const CategoryPage = ({ params }: any) => {
  return <div>Category Page {params.id}</div>;
};

export default CategoryPage;
